// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDonkx1ZjdUmGe0ft1qguyQa7segK77qEc',
    appId: '1:90066681984:web:aeebaba09e6fd163106665',
    messagingSenderId: '90066681984',
    projectId: 'projeto-flutter-baf34',
    authDomain: 'projeto-flutter-baf34.firebaseapp.com',
    storageBucket: 'projeto-flutter-baf34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1hVv7k_sfXkXFWbwUGbH4t2wKbCM15Ss',
    appId: '1:90066681984:android:7335106c1e54493b106665',
    messagingSenderId: '90066681984',
    projectId: 'projeto-flutter-baf34',
    storageBucket: 'projeto-flutter-baf34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLPmx1cnC99GnBRlWjeNUebtA3ogm1R6s',
    appId: '1:90066681984:ios:f1840bb0d92ad90e106665',
    messagingSenderId: '90066681984',
    projectId: 'projeto-flutter-baf34',
    storageBucket: 'projeto-flutter-baf34.firebasestorage.app',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLPmx1cnC99GnBRlWjeNUebtA3ogm1R6s',
    appId: '1:90066681984:ios:f1840bb0d92ad90e106665',
    messagingSenderId: '90066681984',
    projectId: 'projeto-flutter-baf34',
    storageBucket: 'projeto-flutter-baf34.firebasestorage.app',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDonkx1ZjdUmGe0ft1qguyQa7segK77qEc',
    appId: '1:90066681984:web:56078f93ec73b37e106665',
    messagingSenderId: '90066681984',
    projectId: 'projeto-flutter-baf34',
    authDomain: 'projeto-flutter-baf34.firebaseapp.com',
    storageBucket: 'projeto-flutter-baf34.firebasestorage.app',
  );
}
